[tool.poetry]
name = "deimkit"
version = "0.1.1"
description = ""
authors = ["dnth <dickson.neoh@gmail.com>"]
license = ""

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
faster-coco-eval = ">=1.6.5,<2"
pyyaml = ">=6.0.2,<7"
tensorboard = ">=2.19.0,<3"
scipy = ">=1.15.2,<2"
calflops = ">=0.3.2,<0.4"
transformers = ">=4.49.0,<5"
opencv-python = ">=4.11.0.86,<5"
gdown = ">=5.2.0,<6"
loguru = ">=0.7.3,<0.8"
matplotlib = "*"
gradio = ">=5.20.1,<6"
onnxsim = ">=0.4.36,<0.5"

# GPU dependencies for CUDA 11.8
torch = { version = ">=2.5.1", source = "pytorch-cuda118" }
torchvision = { version = ">=0.20.1", source = "pytorch-cuda118" }
onnxruntime-gpu = ">=1.19.2"
tensorrt = ">=10.1.0"
tensorrt-cu12 = ">=10.1.0"
tensorrt-cu12-bindings = ">=10.1.0"
tensorrt-cu12-libs = ">=10.1.0"
torch-pruning = "^1.5.2"
ultralytics = "^8.3.102"
pycuda = "^2025.1"
onnx = ">=1.16.0,<1.17.0"
onnx-graphsurgeon = "^0.5.7"
scikit-learn = "^1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-cuda118"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"
